const motivationalQuotes = [
  "Believe you can.",
  "Stay focused.",
  "Dream big.",
  "You got this.",
  "Never give up.",
  "Keep pushing.",
  "Stay strong.",
  "Make it happen.",
  "Embrace change.",
  "Stay positive.",
  "Think big.",
  "Do your best.",
  "Stay determined.",
  "Learn from failure.",
  "Challenge yourself.",
  "Work hard.",
  "Love what you do.",
  "Enjoy the journey.",
  "Push your limits.",
  "Follow your dreams.",
  "Focus on progress.",
  "Never look back.",
  "Celebrate small victories.",
  "Create your destiny.",
  "Embrace the struggle.",
  "Keep moving forward.",
  "Trust the process.",
  "Keep your head up.",
  "Stay positive always.",
  "Believe in yourself.",
  "Stay hungry, stay foolish.",
  "Act with courage.",
  "Keep going.",
  "You are stronger than you think.",
  "Success is a journey, not a destination.",
  "Your only limit is you.",
  "Dream it. Wish it. Do it.",
  "The best time for new beginnings is now.",
  "Don't stop until you're proud.",
  "Make today so awesome that yesterday gets jealous.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not for the lazy.",
  "You are capable of amazing things.",
  "Believe in the magic within you.",
  "Your vibe attracts your tribe.",
  "Stay true to yourself.",
  "Be the change you wish to see.",
  "Doubt kills more dreams than failure ever will.",
  "You are the artist of your own life.",
  "Turn your wounds into wisdom.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Don't wait for opportunity. Create it.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "The only way to do great work is to love what you do.",
  "Dream it. Believe it. Build it.",
  "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
  "You are enough just as you are.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Success usually comes to those who are too busy to be looking for it.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Act as if what you do makes a difference. It does.",
  "Success is not in what you have, but who you are.",
  "You don't have to be great to start, but you have to start to be great.",
  "The best way to predict the future is to create it.",
  "Your passion is waiting for your courage to catch up.",
  "Don't watch the clock; do what it does. Keep going.",
  "The only person you are destined to become is the person you decide to be.",
  "Believe in your infinite potential.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "You miss 100% of the shots you don't take.",
  "The future depends on what you do today.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Don't limit your challenges. Challenge your limits.",
  "You are the master of your destiny.",
  "The only thing standing between you and your goal is the story you keep telling yourself.",
  "Success is not about being the best. It's about always getting better.",
  "Your time is limited, so don't waste it living someone else's life.",
  "The journey of a thousand miles begins with one step.",
  "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  "Success is not for the chosen few, but for the few who choose.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "You are never too old to set another goal or to dream a new dream.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Success is not about how much money you make, but the difference you make in people's lives.",
  "Believe in yourself and all that you are.",
  "You are capable of more than you know.",
  "The best revenge is massive success.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "You are the author of your own story.",
  "Keep your dreams alive. Understand that to achieve anything requires faith and belief in yourself.",
  "The only limit to your impact is your imagination and commitment.",
  "Success is not about what you have, but what you give.",
  "You are unique, and that is your superpower.",
  "Your life does not get better by chance, it gets better by change.",
  "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
];

export const getRandomQuote = () => {
  const randomIndex = Math.floor(Math.random() * motivationalQuotes.length);
  return motivationalQuotes[randomIndex];
};
